### ISSUE TITLE
Allow opening build reports in Visual Studio from standalone app

### ISSUE THREAD

**Issue by alimbada** [tfsbuildextensions/BuildManager#10]
The standalone app currently shows the message `This feature is not supported when running the stand alone application.`

When TFS sends build failure reports by email, those emails contain links that use the `vstfs://` protocol. Clicking on such a link opens the build report in Visual Studio. The standalone app should also use these links.

A `vstfs` protocol link looks like the following:
`vstfs:///Build/Build/<build_request_number>?url=<team_project_collection_url>`

**Comment by mikefourie** [comment]
Happy to take a pull request for this.

**Comment by alimbada** [comment]
Thanks, pull request submitted.

You may want to leave issues open in the future so that if someone else comes along they can see outstanding issues and take them up if they want to.

**Comment by mikefourie** [comment]
Thanks for the PR. Good point on keeping the bug open. I could do with another state in this interface.

**Comment by alimbada** [comment]
Labels might be what you're looking for: https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/

**Comment by mikefourie** [comment]
Perfect! Thanks!
