### ISSUE TITLE
Error Exporting Build

### ISSUE THREAD

**Issue by NDurham12** [tfsbuildextensions/BuildManager#15]
Hello, 

I have a lot of builds I'm trying to consolidate. When I used your tool, it works great at listing the builds, but when I try to use the export option, I get the following error:

![image](https://cloud.githubusercontent.com/assets/5875789/7211366/c1c4d4f0-e51f-11e4-9b7a-d2fb33534a70.png)

I'm using visual Studio 2013 pointing to TFS 2010

**Comment by mikefourie** [comment]
Hi

TFS2010 isn't supported sorry.

Mike
