### ISSUE TITLE
Allow changing priority of a queued build

### ISSUE THREAD

**Issue by alimbada** [tfsbuildextensions/BuildManager#9]
In the VS Build Explorer when managing the Build Queue you can right-click a queued build and set its priority.

I'd like to be able to use the same functionality from the standalone application as I'm using git and git-tfs for source control so in order to manage the build queue within Visual Studio I'd have to keep switching source control plugins.

**Comment by mikefourie** [comment]
Happy to take a pull request for this.

**Comment by mikefourie** [comment]
re-opened. thanks @alimbada for the labels tip
